blank_issues_enabled: true
contact_links:
    - name: User Guides
      url: https://joshuaestes.github.io/pms/
      about: The user guides contain lots of information on using PMS.
    - name: Developer Guides
      url: https://github.com/JoshuaEstes/pms/wiki
      about: The developer guides have information on creating plugins and themes to be used with PMS.
