# ~/.bashrc
####
#
# .bashrc
#
# This file may get updated when running an install or update, please use
# the config files to modify PMS
#

if [ "$PMS_DEBUG" -eq "1" ]; then
  echo "[DEBUG] PMS Loading ~/.bashrc"
fi

source $PMS/pms.sh bash

if [ "$PMS_DEBUG" -eq "1" ]; then
  echo "[DEBUG] PMS Completed Loading ~/.bashrc"
fi

