# ~/.zshrc
####
# This file may get updated when running an install or pms update, please use
# the config files and PMS_LOCAL directory to modify PMS

# @todo
PMS=~/.pms
PMS_DEBUG=0
source $PMS/pms.sh zsh $PMS_DEBUG
