# ~/.zshrc
####
# This file may get updated when running an install or pms update, please use
# the config files and PMS_LOCAL directory to modify PMS

[[ -f ~/.env ]] && source ~/.env
[[ -f ~/.env.zsh ]] && source ~/.env.zsh
[[ -f ~/.env.local ]] && source ~/.env.local
[[ -f ~/.env.zsh.local ]] && source ~/.env.zsh.local

source $PMS/pms.sh zsh $PMS_DEBUG
