#theme: jekyll-theme-cayman
remote_theme: mmistakes/minimal-mistakes@4.19.2
title: PMS
show_downloads: false
plugins: [jekyll-include-cache]
defaults:
    # _pages
    - scope:
        path: ""
        type: pages
      values:
          layout: single
          sidebar:
              nav: sidebar_default
