name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - run: PMS_DEBUG=1 sh ./scripts/install.sh
      - run: cat /etc/shells
      - run: source ~/.pms/pms.sh bash 1
      - run: PMS_DEBUG=1 pms diagnostic
      - run: PMS_DEBUG=1 sh ~/.pms/scripts/uninstall.sh -n
