name: CI
env:
    PMS_DEBUG: 1
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - run: sh ./scripts/install.sh
      - run: cat /etc/shells
      - run: source ~/.pms/pms.sh bash 1 && pms help
      - run: pms help
      - run: sh ~/.pms/scripts/uninstall.sh -n
